# Generated by Django 4.0.6 on 2022-07-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='descriao',
            new_name='descricao',
        ),
    ]
